language: cpp

os:
  - linux
  - osx

compiler:
  - gcc

matrix:
  include:
    - os: linux
      dist: bionic
    - os: osx
      osx_image: xcode11

script:
  - cmake .
  - cmake --build . --target benchtool_cpp

deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "benchtool_cpp"
  skip_cleanup: true
  overwrite: true
  draft: true