version: 2.1

jobs:
  build-arm:
    machine:
      image: cimg/base:stable-20.04
    resource_class: arm.medium
    steps:
      - checkout
      - run:  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t brunoshiroma/benchtool-cpp:arm64-latest .
      - run: docker push brunoshiroma/benchtool-cpp:arm64-latest

  build-amd64:
    machine:
      image: cimg/base:stable-20.04
    resource_class: medium
    steps:
      - checkout
      - run:  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker build -t brunoshiroma/benchtool-cpp:amd64-latest .
      - run: docker push brunoshiroma/benchtool-cpp:amd64-latest

  push-multi-arch-meta:
    machine:
      image: cimg/base:stable-20.04
    resource_class: small
    steps:
      - run:  echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run: docker manifest create brunoshiroma/benchtool-cpp:latest brunoshiroma/benchtool-cpp:amd64-latest brunoshiroma/benchtool-cpp:arm64-latest
      - run: docker manifest push brunoshiroma/benchtool-cpp:latest

workflows:
  build:
    jobs:
      - build-arm:
          context: benchtool
      - build-amd64:
          context: benchtool
      - push-multi-arch-meta:
          context: benchtool
          requires:
            - build-arm
            - build-amd64